# Generated by Django 5.2 on 2025-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thamnail",
            field=models.FileField(default="", upload_to="videos/thamnail/"),
            preserve_default=False,
        ),
    ]
