# Generated by Django 5.2 on 2025-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_thamnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thamnail",
            field=models.ImageField(upload_to="videos/thamnail/"),
        ),
    ]
