# Generated by Django 5.2 on 2025-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='UserId',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
